### ISSUE TITLE
Could not find the package using either pip or Conda

### ISSUE THREAD

**Issue by axelwang** [jrenaud90/CyRK#44]
Hey. I am trying to install CyRK on an HPC environment. I have pip version 21.3.1.
I tried 
`pip3 install --user CyRK`
and got
`Collecting CyRK
  Could not find a version that satisfies the requirement CyRK (from versions: )
No matching distribution found for CyRK`

Then I tried to use Conda to install the package on my local machine, and got 
`PackagesNotFoundError: The following packages are not available from current channels:

  - cyrk`

Can someone please let me know why this package cannot be found? Thanks!

**Comment by jrenaud90** [comment]
Hey @axelwang - Which version of Python are you using?

Currently CyRK is not available via conda but the pip install should have worked.

**Comment by jrenaud90** [comment]
Closing this for now. Please let me know if you are still having an issue. Thanks!
