### ISSUE TITLE
`t_eval` of `CyRK` behaves different to `solve_ivp`

### ISSUE THREAD

**Issue by fvollmer** [jrenaud90/CyRK#45]
I just figured out that `t_eval` isn't behaving in the same way as `scipy.integrate.solve_ivp`:

`solve_ivp` solves the ode for the points in `t_eval`
>Times at which to store the computed solution, must be sorted and lie within t_span. If None (default), use points selected by the solver.

`CyRK ` interpolates the solution `t_eval`
> Both solvers uses an adaptive time stepping protocol based on the recent error at each step. This results in a final non-uniform time domain of variable size. If the user would like the results at specific time steps then they can provide a np.ndarray array at the desired steps via t_eval. The solver will then interpolate the results to fit this array.

In my kind of special case `CyRK` is actually slower than `solve_ivp`.

**Comment by jrenaud90** [comment]
Hi, @fvollmer! Yes this is a missing feature of CyRK. It would not be too difficult to implement: solve_ivp uses a dense output which estimates the value of your problem inbetween solution steps (sorta like a faster, more accurate interpolation). 

I will mark this as a todo for a future update (PRs are welcome if you or others want to work on this!)

In the mean time feel free to share a simple working example of your code. I would be curious why the interpolation is so severely impacting performance. If you are not using the CySolver approach then that would be a way to greatly improve performance.

Cheers!

**Comment by jrenaud90** [comment]
Hey @fvollmer You have probably found another solution in the interim but this dense output and proper t_eval interpolation has been added in CyRK v.0.10.0. Feel free to give it a try and post if you run into any problems. Closing this issue for now.
