### ISSUE TITLE
PyPI macos wheels changed architecture with 0.8.7

### ISSUE THREAD

**Issue by dihm** [jrenaud90/CyRK#49]
The macos workflow for building wheels is defaulting to whatever the `macos-latest` runner architecture is (which changed recently from x64-86 to arm64). 

I think you could easily distribute both architectures by running the macos workflow on a `macos-latest` and a `macos-13` runner (they have arm64 and x64 architectures natively).

**Comment by jrenaud90** [comment]
Added back MacOS-13 with 0.9.0, let me know if that works for you!

**Comment by dihm** [comment]
That did it! Thanks!
